#!/usr/bin/env python3

# Built in imports
import os
import subprocess
import sys

# Get user who is running script
original_user = os.environ.get('SUDO_USER') or os.getlogin()

HOME_SEARCH = [f"/home/{original_user}/"]

# ANSI colors
YELLOW = "\033[33m"
BLUE = "\033[34m"
RED = "\033[31m"
RESET = "\033[0m" #Reset default to color

# A wrapper for the find_repositories_recursive which allows for the search of multiple parent directories
def find_repositories(directory_list: list, recursive: bool = False) -> list: 
    repositories = []
    
    for directory in directory_list:
        if recursive == True:
            repositories.extend(find_repositories_recursive(directory))
        else:
            if os.path.isdir(directory) == True:
                for child_directory in os.listdir(directory):
                        if os.path.isdir(f"{directory}{child_directory}/.git"):
                            repositories.append(f"{directory}{child_directory}")
    
    return repositories
    
# A recursive function that walks(iterates) through directories to find '.git' directories
def find_repositories_recursive(root: str, repositories: list = None):
    if repositories == None:
        repositories = []
    
    if os.path.isdir(root):
        os.chdir(root)
        for child_directory in os.listdir(root):
            child_path = f"{root}{child_directory}"
            if os.path.isdir(child_path + "/.git"):
                repositories.append(child_path)
            elif os.path.isdir(child_path) and child_directory[0] != ".":
                find_repositories_recursive(child_path + "/", repositories)
    return repositories

def status_repos(repositories: list) -> None:
    for repo in repositories:
        print(f"{YELLOW}[GITY] -> Executing git status on [{repo}]{RESET}")
        try:
            os.chdir(repo)
            status_result = subprocess.run(['git', 'status'], capture_output=True, text=True)
            return_code = subprocess.call(['git', 'status'])
        except Exception as e:
            print(f"{RED}[GITY] -> Error, unable to execute git status on {repo}\n Exception: {e}{RESET}")

def main():
    # Variables
    local_repositories = []
    # Flag variables
    help_arg = False
    version_info = False
    list_local_repos = False
    
    # Set flag variables with arguments
    for arg in sys.argv:
        if arg == "list":
            list_local_repos = True
        if arg == "help":
            help_arg = True
        if arg == "ver" or arg == "version":
            version_info = True

    # Process arguments
    if list_local_repos == True:
        print(f"{YELLOW}All repositories in your home directory:{RESET}")
        for repo in find_repositories(HOME_SEARCH, recursive = True):
            print(f" -- {repo}")
    elif help_arg == True:
        print("Commands: ")
        print(" With no arguments, Gity will execute git status on all repositories.")
        print(" -- List directory search options: gity list")
        print(" -- Get version info: gity [version/ver]")
    elif version_info == True:
        print("Version: 0.1")
        print("Creator: Nolan Provencher")
        print("GitHub: https://github.com/ner216/linux_scripts")
    elif len(sys.argv) == 1:
        local_repositories = find_repositories(HOME_SEARCH, recursive = True)
        # Execute git status on discovered repos
        status_repos(local_repositories)
    else:
        print("Unknown argument given! Use 'gity help' for more information.")

main()

