#!/bin/bash

# Make script exit if command fails
set -e

# Ensure that script is run as root
if [[ $EUID -ne 0 ]]; then
    echo "Script must be run with sudo."
    exit 1
fi

update_ubuntu() {
    printf "[OSUPDATE] Running apt-update\n"
    apt-get update
    printf "[OSUPATE] Running apt-upgrade\n"
    apt-get upgrade
}

update_fedora() {
    printf "[OSUPDATE] Running dnf update\n"
    dnf update
}

update_flatpak() {
    printf "[OSUPDATE] Running flatpak update\n"
    flatpak update
}


if [ -f /etc/os-release ]; then
    . /etc/os-release

    if [ "$ID" = "ubuntu" ]; then
        update_ubuntu
        if command -v flatpak &>/dev/null
        then
            update_flatpak
        fi
    elif [ "$ID" = "fedora" ]; then
        update_fedora
        update_flatpak
    else
        echo "[OSUPATE] Unsupported Distrobution"
        exit 1
    fi
else
    echo "Unable to read /etc/os-release"
    exit 1
fi


